name: Mobs
main: cn.rpgmc.run.Main
version: 3.0.2
commands:
  Mobs:
    description: by owen
    usage: §c§l[Mobs]§5参数错误,您可以使用/Mobs help命令排查错误.
    permission: mobs
    permission-message: §c§l[Mobs]§5您没有<mobs>权限