name: Mobs
main: pw.owen.mobs.run.Main
website: http://www.owen.pw
author: owen
version: 4.1.0
commands:
  Mobs:
    description: by owen
    usage: §c§l[Mobs]§9参数错误,您可以使用/Mobs help命令排查错误.
    permission: mobs
    permission-message: §c§l[Mobs]§5您没有<mobs>权限